PrimeFaces.locales ['it'] = {
     closeText: 'Chiudi',
     prevText: 'Precedente',
     nextText: 'Successivo',
     monthNames: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre' ],
     monthNamesShort: ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic' ],
     dayNames: ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'],
     dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
     dayNamesMin: ['D', 'L', 'M', 'M ', 'G', 'V ', 'S'],
     weekHeader: 'Sett',
     firstDay: 1,
     isRTL: false,
     showMonthAfterYear: false,
     yearSuffix:'',
     timeOnlyTitle: 'Orario',
     timeText: 'Ora',
     hourText: 'Ore',
     minuteText: 'Minuto',
     secondText: 'Secondo',
     currentText: 'Data odierna',
     ampm: false,
     month: 'Mese',
     week: 'Settimana',
     day: 'Giorno',
     allDayText: 'Tutto il giorno'
 };