insert into acc_permesso (permesso, descrizione) values ('lut:*', 'Accesso alle tabelle di lookup');
insert into acc_permesso (permesso, descrizione) values ('permesso:*', 'Gestione permessi completa');
insert into acc_permesso (permesso, descrizione) values ('permesso:create', 'Creazione permessi');
insert into acc_permesso (permesso, descrizione) values ('permesso:delete', 'Cancellazione permessi');
insert into acc_permesso (permesso, descrizione) values ('permesso:get', 'Ottenimento dati permessi');
insert into acc_permesso (permesso, descrizione) values ('permesso:list', 'Lista permessi');
insert into acc_permesso (permesso, descrizione) values ('permesso:update', 'Aggiornamento permessi');
insert into acc_permesso (permesso, descrizione) values ('report:*', 'Funzionalità di reportistica complete');
insert into acc_permesso (permesso, descrizione) values ('report:basictest', 'Report base di test');
insert into acc_permesso (permesso, descrizione) values ('ruolo:*', 'Gestione ruoli completa');
insert into acc_permesso (permesso, descrizione) values ('ruolo:create', 'Creazione ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:delete', 'Cancellazione ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:get', 'Ottenimento dati ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:list', 'Lista ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:update', 'Aggiornamento ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:addpermesso', 'Aggiunta permessi ai ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:deletepermesso', 'Cancellazione permessi dai ruoli');
insert into acc_permesso (permesso, descrizione) values ('ruolo:getpermesso', 'Ottenimento dati permessi dei ruoli');
insert into acc_permesso (permesso, descrizione) values ('utente:*', 'Gestione utenti completa');
insert into acc_permesso (permesso, descrizione) values ('utente:create', 'Creazione utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:delete', 'Cancellazione utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:get', 'Ottenimento dati utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:list', 'Lista utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:update', 'Aggiornamento utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:addruolo', 'Aggiunta ruoli agli utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:deleteruolo', 'Cancellazione ruoli dagli utenti');
insert into acc_permesso (permesso, descrizione) values ('utente:getruolo', 'Ottenimento dei ruoli degli utenti');
