CREATE TABLE gen_provincia
(
	id SERIAL NOT NULL PRIMARY KEY,
  sigla VARCHAR(2) NOT NULL UNIQUE,
  regione VARCHAR(255) NOT NULL,
	descrizione VARCHAR(255) NOT NULL
);


INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TO', 'Piemonte', 'Torino');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VC', 'Piemonte', 'Vercelli');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('NO', 'Piemonte', 'Novara');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CN', 'Piemonte', 'Cuneo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AT', 'Piemonte', 'Asti');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AL', 'Piemonte', 'Alessandria');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BI', 'Piemonte', 'Biella');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VB', 'Piemonte', 'Verbano-Cusio-Ossola');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AO', 'Valle d''Aosta', 'Valle d''Aosta');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VA', 'Lombardia', 'Varese');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CO', 'Lombardia', 'Como');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SO', 'Lombardia', 'Sondrio');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MI', 'Lombardia', 'Milano');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BG', 'Lombardia', 'Bergamo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BS', 'Lombardia', 'Brescia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PV', 'Lombardia', 'Pavia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CR', 'Lombardia', 'Cremona');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MN', 'Lombardia', 'Mantova');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LC', 'Lombardia', 'Lecco');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LO', 'Lombardia', 'Lodi');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MB', 'Lombardia', 'Monza e della Brianza');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BZ', 'Trentino-Alto Adige', 'Bolzano');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TN', 'Trentino-Alto Adige', 'Trento');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VR', 'Veneto', 'Verona');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VI', 'Veneto', 'Vicenza');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BL', 'Veneto', 'Belluno');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TV', 'Veneto', 'Treviso');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VE', 'Veneto', 'Venezia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PD', 'Veneto', 'Padova');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RO', 'Veneto', 'Rovigo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('UD', 'Friuli-Venezia Giulia', 'Udine');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('GO', 'Friuli-Venezia Giulia', 'Gorizia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TS', 'Friuli-Venezia Giulia', 'Trieste');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PN', 'Friuli-Venezia Giulia', 'Pordenone');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('IM', 'Liguria', 'Imperia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SV', 'Liguria', 'Savona');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('GE', 'Liguria', 'Genova');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SP', 'Liguria', 'La Spezia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PC', 'Emilia-Romagna', 'Piacenza');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PR', 'Emilia-Romagna', 'Parma');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RE', 'Emilia-Romagna', 'Reggio nell''Emilia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MO', 'Emilia-Romagna', 'Modena');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BO', 'Emilia-Romagna', 'Bologna');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FE', 'Emilia-Romagna', 'Ferrara');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RA', 'Emilia-Romagna', 'Ravenna');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FC', 'Emilia-Romagna', 'Forlì-Cesena');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RN', 'Emilia-Romagna', 'Rimini');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MS', 'Toscana', 'Massa-Carrara');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LU', 'Toscana', 'Lucca');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PT', 'Toscana', 'Pistoia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FI', 'Toscana', 'Firenze');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LI', 'Toscana', 'Livorno');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PI', 'Toscana', 'Pisa');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AR', 'Toscana', 'Arezzo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SI', 'Toscana', 'Siena');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('GR', 'Toscana', 'Grosseto');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PO', 'Toscana', 'Prato');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PG', 'Umbria', 'Perugia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TR', 'Umbria', 'Terni');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PU', 'Marche', 'Pesaro e Urbino');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AN', 'Marche', 'Ancona');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MC', 'Marche', 'Macerata');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AP', 'Marche', 'Ascoli Piceno');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FM', 'Marche', 'Fermo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VT', 'Lazio', 'Viterbo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RI', 'Lazio', 'Rieti');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RM', 'Lazio', 'Roma');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LT', 'Lazio', 'Latina');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FR', 'Lazio', 'Frosinone');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AQ', 'Abruzzo', 'L''Aquila');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TE', 'Abruzzo', 'Teramo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PE', 'Abruzzo', 'Pescara');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CH', 'Abruzzo', 'Chieti');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CB', 'Molise', 'Campobasso');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('IS', 'Molise', 'Isernia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CE', 'Campania', 'Caserta');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BN', 'Campania', 'Benevento');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('NA', 'Campania', 'Napoli');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AV', 'Campania', 'Avellino');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SA', 'Campania', 'Salerno');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('FG', 'Puglia', 'Foggia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BA', 'Puglia', 'Bari');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TA', 'Puglia', 'Taranto');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BR', 'Puglia', 'Brindisi');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('LE', 'Puglia', 'Lecce');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('BT', 'Puglia', 'Barletta-Andria-Trani');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PZ', 'Basilicata', 'Potenza');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('MT', 'Basilicata', 'Matera');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CS', 'Calabria', 'Cosenza');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CZ', 'Calabria', 'Catanzaro');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RC', 'Calabria', 'Reggio di Calabria');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('KR', 'Calabria', 'Crotone');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VV', 'Calabria', 'Vibo Valentia');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('TP', 'Sicilia', 'Trapani');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('PA', 'Sicilia', 'Palermo');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('ME', 'Sicilia', 'Messina');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('AG', 'Sicilia', 'Agrigento');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CL', 'Sicilia', 'Caltanissetta');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('EN', 'Sicilia', 'Enna');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CT', 'Sicilia', 'Catania');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('RG', 'Sicilia', 'Ragusa');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SR', 'Sicilia', 'Siracusa');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('SS', 'Sardegna', 'Sassari');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('NU', 'Sardegna', 'Nuoro');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CA', 'Sardegna', 'Cagliari');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('OR', 'Sardegna', 'Oristano');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('OT', 'Sardegna', 'Olbia-Tempio');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('OG', 'Sardegna', 'Ogliastra');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('VS', 'Sardegna', 'Medio Campidano');
INSERT INTO gen_provincia (sigla, regione, descrizione) VALUES ('CI', 'Sardegna', 'Carbonia-Iglesias');

